require(lubridate)
require(tm)
require(LDAvis)
require(lda)
require(tidyverse)
require(tidytext)
require(SnowballC)
require(stm)
require(quanteda)
require(textmineR)
require(data.table)

data("stop_words")
source("~/GitHub/I-Have-the-Best-Werds/code/functions/btm_functions.R")
source("~/GitHub/I-Have-the-Best-Werds/code/functions/word_subs.R")
source("~/GitHub/I-Have-the-Best-Werds/code/functions//word_removals.R")
source("~/GitHub/I-Have-the-Best-Werds/code/functions/tm_functions.R")

